# Generated by Django 2.0 on 2019-11-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_moblile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='doc_male.png', upload_to='doctorfinder/img/'),
        ),
    ]
